# Generated by Django 4.1.7 on 2023-03-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_employee_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="others",
            field=models.JSONField(default={}, null=True),
        ),
    ]
