# Generated by Django 4.1.7 on 2023-03-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_employee_others"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
