# Generated by Django 4.1.7 on 2023-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_employee_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="years_of_experience",
            field=models.FloatField(null=True),
        ),
    ]
